version: '3'
services:
  web:
    build: .
    command: python app.py
    depends_on:
      - mongo
      - redis
      - worker
    ports:
     - "5000:5000"
  worker:
    build: .
    command: celery -A app.celery worker
    depends_on:
      - mongo
      - redis
  redis:
    image: "redis"
    expose:
      - "6379"
  mongo:
    image: "mongo"
    expose:
      - "27017"
