version: '3'
services:
  web:
    build: .
    command: python app.py
    env_file:
      - .env
    depends_on:
      - mongo
      - worker
    ports:
      - "5000:5000"
  worker:
    build: .
    command: celery -A app.celery worker
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: "mongo:4.2.0-rc2-bionic"
    expose:
      - "27017"
networks:
  default:
    external:
      name: demo_hydronet